In [1]:
import pandas as pd
df_dataset=pd.read_csv('interviewTaskDataset.csv')
summary_categorical =df_dataset.describe(include='all')
summary_categorical

,participantId,studyVisitNumber,treatment_group,dateSurveyCompleted,ethnicity,smoking_status,eq5d5l_indexScore,haq_activitiesOverall,haq_painRating,haq_healthRating,...,sdmQ9_decisionNeed,sdmQ9_discussedInvolvement,sdmQ9_raisedOptions,sdmQ9_discussedAdvDis,sdmQ9_helpedToUnderstand,sdmQ9_askedPreferences,sdmQ9_discussedOptions,sdmQ9_sharedTreatDecision,sdmQ9_agreedPlan,recordComplete
count,55,55.000000,55.000000,46,34,34,53,53.000000,53.000000,53.000000,...,37.000000,37.000000,37.000000,37.000000,37.000000,36.000000,36.000000,35.000000,37.000000,52.000000
unique,32,NaN,NaN,37,8,5,39,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,TEST001,NaN,NaN,15/05/2023,White British,Former smoker,0.887,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,NaN,NaN,4,26,16,5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.418182,0.436364,NaN,NaN,NaN,NaN,2.188679,4.686792,4.581132,...,4.270270,6.918919,4.189189,3.918919,6.918919,6.305556,6.222222,6.400000,4.216216,0.826923
std,NaN,0.497807,0.500505,NaN,NaN,NaN,NaN,0.941697,2.731021,2.771216,...,0.902116,15.619394,1.329951,1.187396,15.610499,15.931675,15.944746,16.146753,0.916974,0.382005
min,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,...,2.000000,2.000000,1.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000
25%,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,2.000000,2.000000,2.000000,...,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,2.750000,3.000000,4.000000,1.000000
50%,NaN,1.000000,0.000000,NaN,NaN,NaN,NaN,2.000000,5.500000,5.000000,...,4.000000,5.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.000000
75%,NaN,2.000000,1.000000,NaN,NaN,NaN,NaN,3.000000,7.000000,7.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1.000000
max,NaN,2.000000,1.000000,NaN,NaN,NaN,NaN,4.000000,9.000000,9.000000,...,5.000000,99.000000,9.000000,5.000000,99.000000,99.000000,99.000000,99.000000,5.000000,1.000000

In [2]:
df_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   participantId                 55 non-null     object
 1   studyVisitNumber              55 non-null     int64
 2   treatment_group               55 non-null     int64
 3   dateSurveyCompleted           46 non-null     object
 4   ethnicity                     34 non-null     object
 5   smoking_status                34 non-null     object
 6   eq5d5l_indexScore             53 non-null     object
 7   haq_activitiesOverall         53 non-null     float64
 8   haq_painRating                53 non-null     float64
 9   haq_healthRating              53 non-null     float64
 10  haq_disabilityIndex           53 non-null     float64
 11  rapid3_functionalStatusScore  48 non-null     float64
 12  rapid3_painToleranceScore     53 non-null     float64
 13  rapid3_globalEstimateScore    53 non-null     float64
 14  rapid3_cumulativeRapid3Score  48 non-null     float64
 15  rapid3_weightedRapid3Score    48 non-null     float64
 16  rapid3_rapid3Category         55 non-null     object
 17  wpaiRa_isEmployed             55 non-null     object
 18  wpaiRa_hrsMissed_arth         18 non-null     float64
 19  wpaiRa_hrsMissed_other        19 non-null     float64
 20  wpaiRa_hrsWorked              19 non-null     float64
 21  wpaiRa_impact_work            21 non-null     float64
 22  wpaiRa_impact_activities      53 non-null     float64
 23  cdaiTenderCount               41 non-null     float64
 24  cdaiSwollenCount              40 non-null     float64
 25  cdaiPatientGlobal             47 non-null     float64
 26  cdaiPatientPain               47 non-null     float64
 27  sdmQ9_decisionNeed            37 non-null     float64
 28  sdmQ9_discussedInvolvement    37 non-null     float64
 29  sdmQ9_raisedOptions           37 non-null     float64
 30  sdmQ9_discussedAdvDis         37 non-null     float64
 31  sdmQ9_helpedToUnderstand      37 non-null     float64
 32  sdmQ9_askedPreferences        36 non-null     float64
 33  sdmQ9_discussedOptions        36 non-null     float64
 34  sdmQ9_sharedTreatDecision     35 non-null     float64
 35  sdmQ9_agreedPlan              37 non-null     float64
 36  recordComplete                52 non-null     float64
dtypes: float64(28), int64(2), object(7)
memory usage: 16.0+ KB

Missing Critical Field With out of Ranges Values and Different Data formate.

In [3]:
#Missing DataPoint on critical field
df_Missing_Critical_field=df_dataset[['participantId','studyVisitNumber','treatment_group','dateSurveyCompleted','cdaiTenderCount','cdaiSwollenCount', 'cdaiPatientGlobal', 'cdaiPatientPain']]
df_Missing_Critical_field.isna().sum()

participantId           0
studyVisitNumber        0
treatment_group         0
dateSurveyCompleted     9
cdaiTenderCount        14
cdaiSwollenCount       15
cdaiPatientGlobal       8
cdaiPatientPain         8
dtype: int64

In [4]:
df_Missing_Critical_field['dateSurveyCompleted']

0     09/05/1923
1     17/01/2023
2     20/01/2023
3     23/01/2023
4     28/01/2023
5     31/01/2023
6     31/01/2023
7     01/02/2023
8     05/02/2023
9     06/02/2023
10    08/02/2023
11    08/02/2023
12    13/02/2023
13    14/02/2023
14    15/02/2023
15    21/02/2023
16    05/03/2023
17    13/03/2023
18    20/03/2023
19    22/03/2023
20    26/03/2023
21    28/03/2023
22    29/03/2023
23    17/04/2023
24    18/04/2023
25    18/04/2023
26    18/04/2023
27    21/04/2023
28    24/04/2023
29    24/04/2023
30    27/04/2023
31    04/05/2023
32    04/05/2023
33    05/05/2023
34    09/05/2023
35    14/05/2023
36    15/05/2023
37    15/05/2023
38    15/05/2023
39    15/05/2023
40    17/05/2023
41    08/06/2023
42    21/06/2023
43    22/06/2023
44     21/01/203
45    30/02/2023
46           NaN
47           NaN
48           NaN
49           NaN
50           NaN
51           NaN
52           NaN
53           NaN
54           NaN
Name: dateSurveyCompleted, dtype: object

In [5]:
#Participant Miss Vsisit
df_miss_visit= df_Missing_Critical_field['participantId'].value_counts()
unique_ids = df_miss_visit[df_miss_visit == 1].index
df_miss_visit = df_Missing_Critical_field[df_dataset['participantId'].isin(unique_ids)]
df_miss_visit['participantId']

1     TEST002
6     TEST007
10    TEST011
11    TEST012
13    TEST015
19    TEST021
22    TEST024
28    TEST030
30    TEST032
Name: participantId, dtype: object

In [6]:
#incomplete date
for date_str in df_Missing_Critical_field['dateSurveyCompleted']:
    if isinstance(date_str, str) and len(date_str) < 10:
        print(f"Quries incomplete date: '{date_str}'")

Quries incomplete date: '21/01/203'

In [7]:
df_outOf_dateRange = df_Missing_Critical_field[~df_Missing_Critical_field['dateSurveyCompleted'].astype(str).str.contains('2023')]
df_outOf_dateRange[['participantId','dateSurveyCompleted']]

   participantId dateSurveyCompleted
0        TEST001          09/05/1923
44       TEST026           21/01/203
46       TEST019                 NaN
47       TEST018                 NaN
48       TEST028                 NaN
49       TEST008                 NaN
50       TEST031                 NaN
51       TEST025                 NaN
52       TEST003                 NaN
53       TEST033                 NaN
54       TEST005                 NaN

In [8]:
#Clinical Disease activitiy index (CDAI):totao swollen joint count
df_clinicalDease_outOfRange_value=df_Missing_Critical_field[
    (df_Missing_Critical_field['cdaiTenderCount']<0)|
    (df_Missing_Critical_field['cdaiTenderCount']>28)|
    (df_Missing_Critical_field['cdaiSwollenCount']<0)|
    (df_Missing_Critical_field['cdaiSwollenCount']>28)
]
df_clinicalDease_outOfRange_value[['participantId','cdaiTenderCount','cdaiSwollenCount']]

   participantId  cdaiTenderCount  cdaiSwollenCount
16       TEST018             48.0              48.0

In [9]:
# Clinical disease activity index (CDAI: self-reported global health assessment and reported pain Assessment)
df_clinicalDease_outOfRange_pain_golbal=df_Missing_Critical_field[
    (df_Missing_Critical_field['cdaiPatientGlobal']<0)|
    (df_Missing_Critical_field['cdaiPatientGlobal']>10)|
    (df_Missing_Critical_field['cdaiPatientPain']<0)|
    (df_Missing_Critical_field['cdaiPatientPain']>10)
]
df_clinicalDease_outOfRange_pain_golbal[['participantId','cdaiPatientGlobal','cdaiPatientPain']]

Empty DataFrame
Columns: [participantId, cdaiPatientGlobal, cdaiPatientPain]
Index: []

MY doctoe

In [10]:
df_dataset.columns

Index(['participantId', 'studyVisitNumber', 'treatment_group',
       'dateSurveyCompleted', 'ethnicity', 'smoking_status',
       'eq5d5l_indexScore', 'haq_activitiesOverall', 'haq_painRating',
       'haq_healthRating', 'haq_disabilityIndex',
       'rapid3_functionalStatusScore', 'rapid3_painToleranceScore',
       'rapid3_globalEstimateScore', 'rapid3_cumulativeRapid3Score',
       'rapid3_weightedRapid3Score', 'rapid3_rapid3Category',
       'wpaiRa_isEmployed', 'wpaiRa_hrsMissed_arth', 'wpaiRa_hrsMissed_other',
       'wpaiRa_hrsWorked', 'wpaiRa_impact_work', 'wpaiRa_impact_activities',
       'cdaiTenderCount', 'cdaiSwollenCount', 'cdaiPatientGlobal',
       'cdaiPatientPain', 'sdmQ9_decisionNeed', 'sdmQ9_discussedInvolvement',
       'sdmQ9_raisedOptions', 'sdmQ9_discussedAdvDis',
       'sdmQ9_helpedToUnderstand', 'sdmQ9_askedPreferences',
       'sdmQ9_discussedOptions', 'sdmQ9_sharedTreatDecision',
       'sdmQ9_agreedPlan', 'recordComplete'],
      dtype='object')

In [11]:
df_doctor=df_dataset[['participantId','sdmQ9_decisionNeed', 'sdmQ9_discussedInvolvement','sdmQ9_raisedOptions', 'sdmQ9_discussedAdvDis','sdmQ9_helpedToUnderstand', 'sdmQ9_askedPreferences',
       'sdmQ9_discussedOptions', 'sdmQ9_sharedTreatDecision',
       'sdmQ9_agreedPlan']]
df_doctor.isna().sum()

participantId                  0
sdmQ9_decisionNeed            18
sdmQ9_discussedInvolvement    18
sdmQ9_raisedOptions           18
sdmQ9_discussedAdvDis         18
sdmQ9_helpedToUnderstand      18
sdmQ9_askedPreferences        19
sdmQ9_discussedOptions        19
sdmQ9_sharedTreatDecision     20
sdmQ9_agreedPlan              18
dtype: int64

In [12]:
df_doctor = df_dataset[['participantId', 'sdmQ9_decisionNeed', 'sdmQ9_discussedInvolvement','sdmQ9_raisedOptions', 'sdmQ9_discussedAdvDis','sdmQ9_helpedToUnderstand', 'sdmQ9_askedPreferences',
       'sdmQ9_discussedOptions', 'sdmQ9_sharedTreatDecision',
       'sdmQ9_agreedPlan']]
columns_with_99 = df_dataset.columns[df_dataset.eq(99).any()]
df_with_99 = df_dataset[df_dataset[columns_with_99].eq(99).any(axis=1)]
df_with_99

,participantId,studyVisitNumber,treatment_group,dateSurveyCompleted,ethnicity,smoking_status,eq5d5l_indexScore,haq_activitiesOverall,haq_painRating,haq_healthRating,...,sdmQ9_decisionNeed,sdmQ9_discussedInvolvement,sdmQ9_raisedOptions,sdmQ9_discussedAdvDis,sdmQ9_helpedToUnderstand,sdmQ9_askedPreferences,sdmQ9_discussedOptions,sdmQ9_sharedTreatDecision,sdmQ9_agreedPlan,recordComplete
11,TEST012,1,1,08/02/2023,Bangladeshi,Non-smoker,0.916,2.0,5.0,4.0,...,4.0,4.0,4.0,4.0,4.0,99.0,4.0,4.0,4.0,1.0
31,TEST033,1,1,04/05/2023,NaN,Former smoker,0.887,2.0,1.5,3.5,...,5.0,5.0,5.0,5.0,5.0,5.0,99.0,3.0,5.0,1.0
41,TEST006,2,0,08/06/2023,White British,NaN,0.937,2.0,7.0,5.0,...,2.0,2.0,4.0,4.0,4.0,2.0,2.0,99.0,3.0,1.0
54,TEST005,2,0,NaN,White British,NaN,0.623,2.0,6.8,7.5,...,4.0,99.0,4.0,3.0,99.0,3.0,3.0,2.0,4.0,1.0

In [13]:
#out of Ranges Values
df_doctor_outOfrange=df_dataset[['participantId', 'sdmQ9_decisionNeed', 'sdmQ9_discussedInvolvement','sdmQ9_raisedOptions', 'sdmQ9_discussedAdvDis','sdmQ9_helpedToUnderstand', 'sdmQ9_askedPreferences',
       'sdmQ9_discussedOptions', 'sdmQ9_sharedTreatDecision',
       'sdmQ9_agreedPlan']]
# Select the columns of interest
columns_of_interest = ['sdmQ9_decisionNeed', 'sdmQ9_discussedInvolvement',
                       'sdmQ9_raisedOptions', 'sdmQ9_discussedAdvDis', 
                       'sdmQ9_helpedToUnderstand', 'sdmQ9_askedPreferences', 
                       'sdmQ9_discussedOptions', 'sdmQ9_sharedTreatDecision', 
                       'sdmQ9_agreedPlan']

df_dataset[columns_of_interest] = df_dataset[columns_of_interest].apply(pd.to_numeric, errors='coerce')

# Filter the DataFrame for rows where any value in the specified columns is out of the range 1-6
out_of_range_mask = (df_dataset[columns_of_interest] < 1) | (df_dataset[columns_of_interest] > 6)
df_doctor_outOfrange = df_dataset[out_of_range_mask.any(axis=1)]
df_doctor_outOfrange

,participantId,studyVisitNumber,treatment_group,dateSurveyCompleted,ethnicity,smoking_status,eq5d5l_indexScore,haq_activitiesOverall,haq_painRating,haq_healthRating,...,sdmQ9_decisionNeed,sdmQ9_discussedInvolvement,sdmQ9_raisedOptions,sdmQ9_discussedAdvDis,sdmQ9_helpedToUnderstand,sdmQ9_askedPreferences,sdmQ9_discussedOptions,sdmQ9_sharedTreatDecision,sdmQ9_agreedPlan,recordComplete
2,TEST003,1,1,20/01/2023,White British,NaN,0.937,2.0,0.0,6.5,...,4.0,4.0,5.0,5.0,8.0,4.0,5.0,5.0,5.0,1.0
9,TEST010,1,0,06/02/2023,Any other mixed background,Former smoker,0.866,2.0,7.0,6.0,...,4.0,5.0,9.0,5.0,5.0,4.0,4.0,3.0,5.0,NaN
11,TEST012,1,1,08/02/2023,Bangladeshi,Non-smoker,0.916,2.0,5.0,4.0,...,4.0,4.0,4.0,4.0,4.0,99.0,4.0,4.0,4.0,1.0
31,TEST033,1,1,04/05/2023,NaN,Former smoker,0.887,2.0,1.5,3.5,...,5.0,5.0,5.0,5.0,5.0,5.0,99.0,3.0,5.0,1.0
37,TEST027,2,1,15/05/2023,White British,NaN,0.887,2.0,2.5,5.0,...,4.0,9.0,4.0,0.0,8.0,4.0,4.0,4.0,4.0,1.0
40,TEST013,2,0,17/05/2023,African,NaN,0.313,3.0,0.5,4.5,...,5.0,7.0,3.0,5.0,5.0,3.0,3.0,3.0,3.0,1.0
41,TEST006,2,0,08/06/2023,White British,NaN,0.937,2.0,7.0,5.0,...,2.0,2.0,4.0,4.0,4.0,2.0,2.0,99.0,3.0,1.0
54,TEST005,2,0,NaN,White British,NaN,0.623,2.0,6.8,7.5,...,4.0,99.0,4.0,3.0,99.0,3.0,3.0,2.0,4.0,1.0

Eithnicity cleaning check

In [14]:
df_echincity= df_dataset[['participantId','ethnicity']].sort_values('participantId')
df_echincity.isna().sum()

participantId     0
ethnicity        21
dtype: int64

In [15]:
df_echincity

   participantId                    ethnicity
0        TEST001                White British
45       TEST001                          NaN
1        TEST002                          NaN
2        TEST003                White British
52       TEST003                White British
3        TEST004                           25
39       TEST004                          NaN
54       TEST005                White British
4        TEST005                          NaN
41       TEST006                White British
5        TEST006                          NaN
6        TEST007                White British
7        TEST008                White British
49       TEST008                          NaN
38       TEST009                White British
8        TEST009                White British
9        TEST010  Any other mixed background
33       TEST010                White British
10       TEST011                White British
11       TEST012                  Bangladeshi
12       TEST013                White British
40       TEST013                      African
13       TEST015                White British
36       TEST016                          NaN
14       TEST016                White British
35       TEST017                White British
15       TEST017                White British
47       TEST018                          NaN
16       TEST018                          NaN
46       TEST019                   [Declined]
17       TEST019                   [Declined]
18       TEST020                White British
42       TEST020                White British
19       TEST021                White British
43       TEST022                          NaN
20       TEST022                White British
34       TEST023                          NaN
21       TEST023                          NaN
22       TEST024                          NaN
23       TEST025                White British
51       TEST025                White British
44       TEST026                          NaN
24       TEST026                          NaN
37       TEST027                White British
25       TEST027                          NaN
48       TEST028                White British
26       TEST028                White British
27       TEST029                White British
32       TEST029                          NaN
28       TEST030                          NaN
29       TEST031                          NaN
50       TEST031                          NaN
30       TEST032    White and black Caribbean
53       TEST033                    [Unknown]
31       TEST033                          NaN

In [16]:
# Select the columns of interest
df_echincity = df_dataset[['participantId','ethnicity']]
ethnicity_counts = df_echincity['ethnicity'].value_counts()
df_ethnicity_counts = pd.DataFrame({'Ethnicity': ethnicity_counts.index, 'Count': ethnicity_counts.values})
print(df_ethnicity_counts)

#1 = White British 
#2 = White Irish 
#3 = Any other white background 
#4 = Indian 
#5 = Pakistani 
#6 = Bangladeshi 
#7 = Any other Asian background 
#8 = Chinese 
#9 = Caribbean 
#10 = African 
#11 = Any other black background 
#12 = White and black Caribbean 
#13 = White and black African 
#14 = White and Asian 
#15 = Any other mixed background 
#16 = Any other ethnic group 

# in the echnicity column i was expecting a numric values as this is coded from 1-16 instead of string.
#       Ethnicity  Count
#              White British     26
#                  [Declined]      2
#                          25      1
# Any other mixed background       1
#                  Bangladeshi      1
#   White and black Caribbean      1
#                     African      1
#                   [Unknown]      1
#in this columns i found out there has been inconsity of diferent datatype numric and string thus i see the columns as object
#there have also been deffren eithnicity put for that same individual. to avoid this there should be validation check to be put in place not only that information like eithnccity and gender should only be collected onece and pipe to differnet form rather than taking in multple time

                     Ethnicity  Count
0                White British     26
1                   [Declined]      2
2                           25      1
3  Any other mixed background       1
4                  Bangladeshi      1
5    White and black Caribbean      1
6                      African      1
7                    [Unknown]      1

In [17]:
df_RangeCheckZeroTen=df_dataset[['participantId','haq_painRating','haq_healthRating','rapid3_functionalStatusScore','rapid3_painToleranceScore',
                                 'rapid3_globalEstimateScore','rapid3_weightedRapid3Score',
                                 'wpaiRa_impact_work','wpaiRa_impact_activities']]

In [18]:
df_RangeCheckZeroTen.min()

participantId                   TEST001
haq_painRating                      0.0
haq_healthRating                    0.0
rapid3_functionalStatusScore        3.3
rapid3_painToleranceScore           0.0
rapid3_globalEstimateScore          0.0
rapid3_weightedRapid3Score          1.2
wpaiRa_impact_work                  0.0
wpaiRa_impact_activities            0.0
dtype: object

In [19]:
df_RangeCheckZeroTen.max()

participantId                   TEST033
haq_painRating                      9.0
haq_healthRating                    9.0
rapid3_functionalStatusScore       10.7
rapid3_painToleranceScore           9.0
rapid3_globalEstimateScore          9.0
rapid3_weightedRapid3Score          8.6
wpaiRa_impact_work                 10.0
wpaiRa_impact_activities           10.0
dtype: object

In [20]:
df_RangeCheckZeroTen.isna().sum()

participantId                    0
haq_painRating                   2
haq_healthRating                 2
rapid3_functionalStatusScore     7
rapid3_painToleranceScore        2
rapid3_globalEstimateScore       2
rapid3_weightedRapid3Score       7
wpaiRa_impact_work              34
wpaiRa_impact_activities         2
dtype: int64

In [21]:
df_RangeCheckZeroTen

,participantId,haq_painRating,haq_healthRating,rapid3_functionalStatusScore,rapid3_painToleranceScore,rapid3_globalEstimateScore,rapid3_weightedRapid3Score,wpaiRa_impact_work,wpaiRa_impact_activities
0,TEST001,5.5,6.0,4.7,5.0,1.0,3.6,NaN,3.0
1,TEST002,NaN,NaN,4.0,1.0,1.0,2.0,NaN,2.0
2,TEST003,0.0,6.5,4.3,7.5,7.5,6.4,10.0,7.0
3,TEST004,7.5,7.0,7.0,7.0,5.0,6.3,8.0,7.0
4,TEST005,6.0,5.5,5.0,2.5,7.5,5.0,NaN,3.0
5,TEST006,7.5,5.0,6.3,4.0,3.5,4.6,NaN,4.0
6,TEST007,4.5,2.5,6.3,3.0,4.5,4.6,NaN,3.0
7,TEST008,9.0,0.0,6.3,6.5,6.0,6.3,NaN,5.0
8,TEST009,7.0,7.5,8.3,8.0,6.0,7.4,NaN,9.0
9,TEST010,7.0,6.0,7.3,6.0,5.0,6.1,7.0,7.0
10,TEST011,7.0,7.5,9.0,6.7,6.0,7.2,NaN,8.0
11,TEST012,5.0,4.0,5.7,6.0,7.0,6.2,NaN,7.0
12,TEST013,0.5,7.0,7.0,6.0,7.0,6.7,5.0,5.0
13,TEST015,1.0,0.0,4.0,1.0,0.5,1.8,2.0,1.0
14,TEST016,5.0,6.0,8.3,7.5,7.5,7.8,NaN,9.0
15,TEST017,6.7,9.0,10.0,4.0,3.5,5.8,NaN,10.0
16,TEST018,6.0,0.8,6.3,5.5,6.0,5.9,NaN,4.0
17,TEST019,1.2,7.5,4.0,6.0,6.0,5.3,5.0,5.0
18,TEST020,6.0,6.5,4.3,8.0,2.5,4.9,NaN,3.0
19,TEST021,6.5,7.0,5.7,6.0,5.5,5.7,6.0,6.0
20,TEST022,6.7,7.0,4.3,1.5,1.5,2.4,NaN,1.0
21,TEST023,8.0,8.0,6.7,7.0,5.0,6.2,NaN,7.0
22,TEST024,4.0,1.0,6.7,8.0,7.5,7.4,NaN,7.0
23,TEST025,7.5,0.5,4.0,6.0,7.0,5.7,7.0,5.0
24,TEST026,5.0,0.5,3.7,0.0,0.0,1.2,NaN,1.0
25,TEST027,0.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
26,TEST028,0.0,7.5,4.7,5.0,7.0,5.6,6.0,6.0
27,TEST029,7.5,7.5,3.7,1.2,0.8,1.9,NaN,2.0
28,TEST030,6.0,6.0,NaN,0.0,9.0,NaN,NaN,3.0
29,TEST031,2.0,2.5,NaN,5.0,4.0,NaN,2.0,2.0
30,TEST032,5.0,7.5,4.7,4.0,4.0,4.2,3.0,1.0
31,TEST033,1.5,3.5,4.3,0.5,0.5,1.8,0.0,0.0
32,TEST029,0.7,6.5,9.3,9.0,7.0,8.4,NaN,10.0
33,TEST010,1.0,0.5,7.7,7.0,7.0,7.2,NaN,7.0
34,TEST023,4.0,5.0,3.7,0.0,0.0,1.2,NaN,1.0
35,TEST017,2.0,2.0,4.0,2.0,2.0,2.7,1.0,1.0
36,TEST016,3.0,2.5,5.3,6.5,8.0,6.6,7.0,3.0
37,TEST027,2.5,5.0,3.3,0.7,0.5,1.5,1.0,0.0
38,TEST009,5.0,NaN,NaN,0.0,0.0,NaN,NaN,0.0
39,TEST004,6.0,1.0,3.7,4.5,3.5,3.9,NaN,1.0
40,TEST013,0.5,4.5,4.7,7.5,7.5,6.6,NaN,4.0
41,TEST006,7.0,5.0,4.7,8.0,8.0,6.9,2.0,4.0
42,TEST020,8.0,7.5,NaN,5.0,2.5,NaN,1.0,3.0
43,TEST022,6.5,0.0,10.7,7.5,7.5,8.6,NaN,8.0
44,TEST026,0.0,1.5,3.3,6.0,5.0,4.8,4.0,5.0
45,TEST001,NaN,2.0,3.3,0.5,0.5,1.4,0.0,0.0
46,TEST019,4.0,3.5,7.3,7.8,6.5,7.2,NaN,8.0
47,TEST018,8.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN
48,TEST028,6.0,7.0,8.0,2.5,7.5,6.0,NaN,10.0
49,TEST008,8.0,3.5,4.0,1.0,0.0,1.7,NaN,2.0
50,TEST031,7.8,6.0,6.0,7.0,6.5,6.5,6.0,5.0
51,TEST025,1.0,0.0,NaN,2.0,2.0,NaN,NaN,3.0
52,TEST003,6.0,8.0,7.7,5.0,7.5,6.7,NaN,7.0
53,TEST033,2.5,0.5,6.3,6.7,6.5,6.5,NaN,7.0
54,TEST005,6.8,7.5,4.7,6.8,2.5,4.7,7.0,6.0

In [22]:
df_RangeCheckZeroTen=df_RangeCheckZeroTen[
    (df_RangeCheckZeroTen['haq_painRating']>10)|                     
    (df_RangeCheckZeroTen['haq_healthRating']>10)|                    
    (df_RangeCheckZeroTen['rapid3_functionalStatusScore']>10)|      
    (df_RangeCheckZeroTen['rapid3_painToleranceScore']>10)|           
    (df_RangeCheckZeroTen['rapid3_globalEstimateScore']>10)|                
    (df_RangeCheckZeroTen['rapid3_weightedRapid3Score']>10)|          
    (df_RangeCheckZeroTen['wpaiRa_impact_work']>10)|                  
    (df_RangeCheckZeroTen['wpaiRa_impact_activities']>10)       

]
df_RangeCheckZeroTen

,participantId,haq_painRating,haq_healthRating,rapid3_functionalStatusScore,rapid3_painToleranceScore,rapid3_globalEstimateScore,rapid3_weightedRapid3Score,wpaiRa_impact_work,wpaiRa_impact_activities
43,TEST022,6.5,0.0,10.7,7.5,7.5,8.6,NaN,8.0

In [23]:
df_zeroToonesixeight=df_dataset[['participantId','wpaiRa_hrsMissed_arth','wpaiRa_hrsMissed_other','wpaiRa_hrsWorked']]
df_zeroToonesixeight.min()

participantId             TEST001
wpaiRa_hrsMissed_arth         0.0
wpaiRa_hrsMissed_other        0.0
wpaiRa_hrsWorked              0.0
dtype: object

In [24]:
df_zeroToonesixeight.max()

participantId             TEST033
wpaiRa_hrsMissed_arth        11.5
wpaiRa_hrsMissed_other        8.0
wpaiRa_hrsWorked             45.0
dtype: object

In [25]:
df_zeroToonesixeight.isna().sum()

participantId              0
wpaiRa_hrsMissed_arth     37
wpaiRa_hrsMissed_other    36
wpaiRa_hrsWorked          36
dtype: int64

In [26]:
df_ZeroTOthirty=df_dataset[['participantId','rapid3_cumulativeRapid3Score']]
df_ZeroTOthirty.isna().sum()

participantId                   0
rapid3_cumulativeRapid3Score    7
dtype: int64

In [27]:
df_yes_no=df_dataset[['participantId','wpaiRa_isEmployed','recordComplete']].sort_values('participantId')
df_yes_no
#wpaiRa_isEmployed noted vilidated as i have different formated values and this can be fixed by validating the datatype. this i was expected nureic values o and again a

   participantId wpaiRa_isEmployed  recordComplete
0        TEST001                No             0.0
45       TEST001               Yes             1.0
1        TEST002                No             0.0
2        TEST003               Yes             1.0
52       TEST003         [Unknown]             1.0
3        TEST004               Yes             0.0
39       TEST004                No             0.0
54       TEST005               Yes             1.0
4        TEST005                No             1.0
41       TEST006               Yes             1.0
5        TEST006                No             1.0
6        TEST007                No             1.0
7        TEST008                No             1.0
49       TEST008                No             0.0
38       TEST009         [Unknown]             0.0
8        TEST009                No             1.0
9        TEST010               Yes             NaN
33       TEST010                No             NaN
10       TEST011                No             1.0
11       TEST012                No             1.0
12       TEST013               Yes             1.0
40       TEST013                No             1.0
13       TEST015               Yes             NaN
36       TEST016               Yes             1.0
14       TEST016                No             1.0
35       TEST017               Yes             1.0
15       TEST017                No             1.0
47       TEST018         [Unknown]             1.0
16       TEST018                No             1.0
46       TEST019                No             1.0
17       TEST019               Yes             0.0
18       TEST020                No             1.0
42       TEST020               Yes             1.0
19       TEST021               Yes             1.0
43       TEST022                No             1.0
20       TEST022                No             1.0
34       TEST023                No             1.0
21       TEST023                No             1.0
22       TEST024                No             1.0
23       TEST025               Yes             1.0
51       TEST025                No             1.0
44       TEST026               Yes             0.0
24       TEST026         [Unknown]             1.0
37       TEST027               Yes             1.0
25       TEST027         [Unknown]             1.0
48       TEST028                No             1.0
26       TEST028               Yes             1.0
27       TEST029                No             1.0
32       TEST029                No             0.0
28       TEST030                No             1.0
29       TEST031               Yes             1.0
50       TEST031               Yes             1.0
30       TEST032               Yes             1.0
53       TEST033                No             1.0
31       TEST033               Yes             1.0

In [28]:
df_yes_no.isna().sum()

participantId        0
wpaiRa_isEmployed    0
recordComplete       3
dtype: int64

In [29]:
df_ZeroToThree_Range=df_dataset[['participantId','studyVisitNumber','haq_disabilityIndex','rapid3_rapid3Category','smoking_status']].sort_values('participantId')
df_ZeroToThree_Range
#piping problem result in consistensie eg.
 #TEST008	1.750	Low Severity (LS)	Non-smoker
 #TEST008	1.000	High Severity (HS)	Former smoker
#vilidation problem on both columss rapid3_rapid3Category smoking_status as i was expecting numeric value to show

,participantId,studyVisitNumber,haq_disabilityIndex,rapid3_rapid3Category,smoking_status
0,TEST001,1,3.000,Moderate Severity (MS),Former smoker
45,TEST001,2,2.625,Low Severity (LS),Former smoker
1,TEST002,1,NaN,Low Severity (LS),NaN
2,TEST003,1,3.000,High Severity (HS),NaN
52,TEST003,2,1.875,High Severity (HS),NaN
3,TEST004,1,1.750,High Severity (HS),Former smoker
39,TEST004,2,1.000,Moderate Severity (MS),Former smoker
54,TEST005,2,2.000,High Severity (HS),NaN
4,TEST005,1,2.250,High Severity (HS),NaN
41,TEST006,2,2.500,High Severity (HS),NaN
5,TEST006,1,2.375,High Severity (HS),Former smoker
6,TEST007,1,1.750,High Severity (HS),NaN
7,TEST008,1,1.000,High Severity (HS),Former smoker
49,TEST008,2,1.750,Low Severity (LS),Non-smoker
38,TEST009,2,NaN,[Unknown],Former smoker
8,TEST009,1,1.750,High Severity (HS),Non-smoker
9,TEST010,1,2.625,High Severity (HS),Former smoker
33,TEST010,2,1.000,High Severity (HS),Non-smoker
10,TEST011,1,2.500,High Severity (HS),NaN
11,TEST012,1,1.625,High Severity (HS),Non-smoker
12,TEST013,1,2.125,High Severity (HS),Current smoker
40,TEST013,2,2.750,High Severity (HS),NaN
13,TEST015,1,1.500,Low Severity (LS),NaN
36,TEST016,2,1.625,High Severity (HS),NaN
14,TEST016,1,2.125,High Severity (HS),NaN
35,TEST017,2,1.125,Moderate Severity (MS),NaN
15,TEST017,1,1.500,High Severity (HS),Former smoker
47,TEST018,2,2.375,[Unknown],Non-smoker
16,TEST018,1,1.500,High Severity (HS),Non-smoker
46,TEST019,2,2.500,High Severity (HS),Former smoker
17,TEST019,1,3.375,High Severity (HS),Former smoker
18,TEST020,1,2.250,High Severity (HS),NaN
42,TEST020,2,2.000,[Unknown],NaN
19,TEST021,1,3.125,High Severity (HS),Non-smoker
43,TEST022,2,1.375,High Severity (HS),Former smoker
20,TEST022,1,2.375,Moderate Severity (MS),Non-smoker
34,TEST023,2,2.250,Low Severity (LS),Non-smoker
21,TEST023,1,2.250,High Severity (HS),Non-smoker
22,TEST024,1,1.500,High Severity (HS),NaN
23,TEST025,1,1.250,High Severity (HS),4
51,TEST025,2,1.250,[Unknown],4
44,TEST026,2,1.000,High Severity (HS),Former smoker
24,TEST026,1,1.500,Low Severity (LS),Non-smoker
37,TEST027,2,1.125,Low Severity (LS),NaN
25,TEST027,1,1.875,[Unknown],NaN
48,TEST028,2,1.625,High Severity (HS),NaN
26,TEST028,1,1.875,High Severity (HS),NaN
27,TEST029,1,2.125,Low Severity (LS),Current smoker
32,TEST029,2,2.125,High Severity (HS),Former smoker
28,TEST030,1,1.750,[Unknown],Non-smoker
29,TEST031,1,1.750,[Unknown],Former smoker
50,TEST031,2,1.250,High Severity (HS),Current smoker
30,TEST032,1,1.750,High Severity (HS),99
53,TEST033,2,1.625,High Severity (HS),NaN
31,TEST033,1,3.625,Low Severity (LS),Former smoker

In [30]:

df_ZeroToThree_Range=df_ZeroToThree_Range[['participantId','rapid3_rapid3Category',	'smoking_status']]
df_ZeroToThree_Range.isna().sum()

participantId             0
rapid3_rapid3Category     0
smoking_status           21
dtype: int64

In [31]:
df_ZeroToThree_Range

   participantId   rapid3_rapid3Category  smoking_status
0        TEST001  Moderate Severity (MS)   Former smoker
45       TEST001       Low Severity (LS)   Former smoker
1        TEST002       Low Severity (LS)             NaN
2        TEST003      High Severity (HS)             NaN
52       TEST003      High Severity (HS)             NaN
3        TEST004      High Severity (HS)   Former smoker
39       TEST004  Moderate Severity (MS)   Former smoker
54       TEST005      High Severity (HS)             NaN
4        TEST005      High Severity (HS)             NaN
41       TEST006      High Severity (HS)             NaN
5        TEST006      High Severity (HS)   Former smoker
6        TEST007      High Severity (HS)             NaN
7        TEST008      High Severity (HS)   Former smoker
49       TEST008       Low Severity (LS)      Non-smoker
38       TEST009               [Unknown]   Former smoker
8        TEST009      High Severity (HS)      Non-smoker
9        TEST010      High Severity (HS)   Former smoker
33       TEST010      High Severity (HS)      Non-smoker
10       TEST011      High Severity (HS)             NaN
11       TEST012      High Severity (HS)      Non-smoker
12       TEST013      High Severity (HS)  Current smoker
40       TEST013      High Severity (HS)             NaN
13       TEST015       Low Severity (LS)             NaN
36       TEST016      High Severity (HS)             NaN
14       TEST016      High Severity (HS)             NaN
35       TEST017  Moderate Severity (MS)             NaN
15       TEST017      High Severity (HS)   Former smoker
47       TEST018               [Unknown]      Non-smoker
16       TEST018      High Severity (HS)      Non-smoker
46       TEST019      High Severity (HS)   Former smoker
17       TEST019      High Severity (HS)   Former smoker
18       TEST020      High Severity (HS)             NaN
42       TEST020               [Unknown]             NaN
19       TEST021      High Severity (HS)      Non-smoker
43       TEST022      High Severity (HS)   Former smoker
20       TEST022  Moderate Severity (MS)      Non-smoker
34       TEST023       Low Severity (LS)      Non-smoker
21       TEST023      High Severity (HS)      Non-smoker
22       TEST024      High Severity (HS)             NaN
23       TEST025      High Severity (HS)               4
51       TEST025               [Unknown]               4
44       TEST026      High Severity (HS)   Former smoker
24       TEST026       Low Severity (LS)      Non-smoker
37       TEST027       Low Severity (LS)             NaN
25       TEST027               [Unknown]             NaN
48       TEST028      High Severity (HS)             NaN
26       TEST028      High Severity (HS)             NaN
27       TEST029       Low Severity (LS)  Current smoker
32       TEST029      High Severity (HS)   Former smoker
28       TEST030               [Unknown]      Non-smoker
29       TEST031               [Unknown]   Former smoker
50       TEST031      High Severity (HS)  Current smoker
30       TEST032      High Severity (HS)              99
53       TEST033      High Severity (HS)             NaN
31       TEST033       Low Severity (LS)   Former smoker

In [32]:
df_eq5d5l_indexScore=df_dataset[['participantId','eq5d5l_indexScore']]
df_eq5d5l_indexScore

   participantId eq5d5l_indexScore
0        TEST001             0.197
1        TEST002             0.874
2        TEST003             0.937
3        TEST004             0.879
4        TEST005              0.73
5        TEST006               NaN
6        TEST007             0.775
7        TEST008             0.593
8        TEST009             0.326
9        TEST010             0.866
10       TEST011            -0.937
11       TEST012             0.916
12       TEST013             0.727
13       TEST015             0.887
14       TEST016             0.808
15       TEST017             0.624
16       TEST018             0.779
17       TEST019             0.937
18       TEST020             0.619
19       TEST021             0.829
20       TEST022            -0.153
21       TEST023             0.887
22       TEST024                 1
23       TEST025             0.652
24       TEST026             0.738
25       TEST027             0.733
26       TEST028             0.758
27       TEST029             0.808
28       TEST030             0.669
29       TEST031             0.579
30       TEST032                 1
31       TEST033             0.887
32       TEST029             0.113
33       TEST010             1.829
34       TEST023             0.751
35       TEST017             0.937
36       TEST016             0.777
37       TEST027             0.887
38       TEST009             0.507
39       TEST004             0.619
40       TEST013             0.313
41       TEST006             0.937
42       TEST020            -0.937
43       TEST022             0.887
44       TEST026             0.641
45       TEST001            0.6.67
46       TEST019             0.227
47       TEST018             0.829
48       TEST028             0.837
49       TEST008             0.811
50       TEST031             0.779
51       TEST025             0.406
52       TEST003                 1
53       TEST033               NaN
54       TEST005             0.623

In [33]:
df_eq5d5l_indexScore.isna().sum()

participantId        0
eq5d5l_indexScore    2
dtype: int64

In [34]:
df_eq5d5l_indexScore=df_eq5d5l_indexScore[
    (df_eq5d5l_indexScore['eq5d5l_indexScore']>'1')|
    (df_eq5d5l_indexScore['eq5d5l_indexScore']<'-0.594')
]
df_eq5d5l_indexScore
#out of range value 
#missing value

   participantId eq5d5l_indexScore
20       TEST022            -0.153
33       TEST010             1.829

In [35]:
df_oneTofive=df_dataset[['participantId','haq_activitiesOverall']]
df_oneTofive.isna().sum()
#missing data

participantId            0
haq_activitiesOverall    2
dtype: int64

In [36]:
df_oneTofive

   participantId  haq_activitiesOverall
0        TEST001                    2.0
1        TEST002                    2.0
2        TEST003                    2.0
3        TEST004                    2.0
4        TEST005                    1.0
5        TEST006                    3.0
6        TEST007                    3.0
7        TEST008                    1.0
8        TEST009                    4.0
9        TEST010                    2.0
10       TEST011                    3.0
11       TEST012                    2.0
12       TEST013                    2.0
13       TEST015                    1.0
14       TEST016                    NaN
15       TEST017                    2.0
16       TEST018                    1.0
17       TEST019                    2.0
18       TEST020                    3.0
19       TEST021                    3.0
20       TEST022                    1.0
21       TEST023                    4.0
22       TEST024                    3.0
23       TEST025                    1.0
24       TEST026                    1.0
25       TEST027                    2.0
26       TEST028                    2.0
27       TEST029                    3.0
28       TEST030                    1.0
29       TEST031                    2.0
30       TEST032                    2.0
31       TEST033                    2.0
32       TEST029                    4.0
33       TEST010                    2.0
34       TEST023                    4.0
35       TEST017                    1.0
36       TEST016                    2.0
37       TEST027                    2.0
38       TEST009                    4.0
39       TEST004                    1.0
40       TEST013                    3.0
41       TEST006                    2.0
42       TEST020                    3.0
43       TEST022                    1.0
44       TEST026                    2.0
45       TEST001                    3.0
46       TEST019                    1.0
47       TEST018                    1.0
48       TEST028                    2.0
49       TEST008                    2.0
50       TEST031                    3.0
51       TEST025                    2.0
52       TEST003                    4.0
53       TEST033                    NaN
54       TEST005                    2.0